### ISSUE TITLE
on createmigrations, 'NoneType' object has no attribute '_meta' 

### ISSUE THREAD

**Issue by andytwoods** [codingjoe/django-mail-auth#15]
Hi there,
nice package! I really like the concept.
I get the below when I run python manage.py makemigrations (Django 3.1).
```
  File "C:\Users\andytwoods\PycharmProjects\pubpubs\VE\lib\site-packages\django\contrib\admin\checks.py", line 351, in _check_field_spec_item
    not field.remote_field.through._meta.auto_created):
AttributeError: 'NoneType' object has no attribute '_meta'
```
when I change line 57 of  mailauth.contrib.user.models.py from
```
    class Meta(AbstractUser.Meta):
        abstract = True
```
to

    class Meta(AbstractUser.Meta):
        pass

the error goes away.

Can you foresee any issue with that change? I'll make a pull request.

cheers,
Andy.

**Comment by codingjoe** [comment]
Hi @andytwoods,

Hey, didn't I see you face before 😉 

I am using this package on Django 3.1, and I am not having the same problem you have. Could you place share a bit more information about your setup?

I am afraid removing the `abstract = True` will cause Django create a table for the model. Django's BaseModel (metaclass) adds some dark magic to meta inheritance, see also:
https://docs.djangoproject.com/en/3.1/topics/db/models/#meta-inheritance

I will use the opportunity to upgrade the test suite to officially support Django 3.1.

Best,
Joe
